from __future__ import annotations
from datetime import datetime
from app.models import Repo, Pin


async def generate_report(repo: Repo, pins: list[Pin]) -> str:
    """
    Generate a Markdown architecture report for a repo.
    Includes: summary, language breakdown, top modules, and pinned annotations.
    """
    lines: list[str] = [
        f"# Architecture Report: {repo.name}",
        f"_Generated by YASML on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}_",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Total Files | {repo.file_count} |",
        f"| Total Functions | {repo.function_count} |",
        f"| Dependency Clusters | {repo.cluster_count} |",
        f"| Status | {repo.status} |",
        "",
        "---",
        "",
        "## Language Breakdown",
        "",
    ]

    for lang, count in sorted(
        (repo.language_breakdown or {}).items(), key=lambda x: -x[1]
    ):
        lines.append(f"- **{lang}**: {count} files")

    lines += [
        "",
        "---",
        "",
        "## Top Modules (by size)",
        "",
    ]
    for module in (repo.top_modules or []):
        lines.append(f"- `{module}`")

    if pins:
        lines += [
            "",
            "---",
            "",
            "## Team Annotations",
            "",
            "_Pinned Q&A pairs from the exploration session:_",
            "",
        ]
        for pin in pins:
            lines += [
                f"### {pin.question}",
                "",
                pin.answer,
                "",
                "**Cited references:**",
            ]
            for ref in pin.cited_refs:
                r = ref.get("ref", ref.get("file_path", "?"))
                lines.append(f"- `{r}`")
            lines += [
                "",
                f"_Pinned on: {pin.created_at.strftime('%Y-%m-%d')}_",
                f"{'> ⚠️ This annotation may be stale due to recent code changes.' if pin.is_stale else ''}",
                "",
                "---",
                "",
            ]

    return "\n".join(lines)
